# Generated by Django 6.0.3 on 2026-03-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Wiki Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('article_type', models.CharField(choices=[('disease', 'Disease / Condition'), ('term', 'Medical Term'), ('drug', 'Drug / Medication')], default='disease', max_length=20)),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('overview', models.TextField()),
                ('symptoms', models.TextField(blank=True)),
                ('causes', models.TextField(blank=True)),
                ('risk_factors', models.TextField(blank=True)),
                ('treatments', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('lifestyle_tips', models.TextField(blank=True)),
                ('when_to_see_doctor', models.TextField(blank=True)),
                ('related_tests', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='wiki.wikicategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
