# symptom_checker/symptom_data.py
# Comprehensive symptom-condition ML knowledge base

# All available symptoms with categories
SYMPTOMS = {
    # HEAD & BRAIN
    "headache": {"label": "Headache", "body_part": "head", "emoji": "🤕"},
    "severe_headache": {"label": "Severe / Sudden Headache", "body_part": "head", "emoji": "🤯"},
    "dizziness": {"label": "Dizziness / Lightheadedness", "body_part": "head", "emoji": "😵"},
    "confusion": {"label": "Confusion / Disorientation", "body_part": "head", "emoji": "🧠"},
    "memory_loss": {"label": "Memory Problems", "body_part": "head", "emoji": "🧠"},
    "fainting": {"label": "Fainting / Loss of Consciousness", "body_part": "head", "emoji": "😶"},
    "blurred_vision": {"label": "Blurred Vision", "body_part": "head", "emoji": "👁️"},
    "double_vision": {"label": "Double Vision", "body_part": "head", "emoji": "👁️"},

    # FACE & THROAT
    "facial_swelling": {"label": "Facial Swelling", "body_part": "head", "emoji": "😶"},
    "sore_throat": {"label": "Sore Throat", "body_part": "chest", "emoji": "🤒"},
    "difficulty_swallowing": {"label": "Difficulty Swallowing", "body_part": "chest", "emoji": "😣"},
    "hoarse_voice": {"label": "Hoarse Voice", "body_part": "chest", "emoji": "🗣️"},

    # CHEST
    "chest_pain": {"label": "Chest Pain / Pressure", "body_part": "chest", "emoji": "💔"},
    "chest_tightness": {"label": "Chest Tightness", "body_part": "chest", "emoji": "💔"},
    "palpitations": {"label": "Heart Palpitations / Racing Heart", "body_part": "chest", "emoji": "💓"},
    "irregular_heartbeat": {"label": "Irregular Heartbeat", "body_part": "chest", "emoji": "💓"},
    "shortness_of_breath": {"label": "Shortness of Breath", "body_part": "chest", "emoji": "😮‍💨"},
    "cough": {"label": "Cough", "body_part": "chest", "emoji": "🤧"},
    "dry_cough": {"label": "Dry / Persistent Cough", "body_part": "chest", "emoji": "😮‍💨"},
    "coughing_blood": {"label": "Coughing Blood", "body_part": "chest", "emoji": "🚨"},
    "wheezing": {"label": "Wheezing", "body_part": "chest", "emoji": "😮‍💨"},

    # ABDOMEN
    "abdominal_pain": {"label": "Abdominal Pain / Stomach Pain", "body_part": "abdomen", "emoji": "😣"},
    "upper_abdominal_pain": {"label": "Upper Abdominal Pain", "body_part": "abdomen", "emoji": "😣"},
    "lower_abdominal_pain": {"label": "Lower Abdominal Pain", "body_part": "abdomen", "emoji": "😣"},
    "nausea": {"label": "Nausea", "body_part": "abdomen", "emoji": "🤢"},
    "vomiting": {"label": "Vomiting", "body_part": "abdomen", "emoji": "🤮"},
    "diarrhea": {"label": "Diarrhea", "body_part": "abdomen", "emoji": "🚽"},
    "constipation": {"label": "Constipation", "body_part": "abdomen", "emoji": "😣"},
    "bloating": {"label": "Bloating / Gas", "body_part": "abdomen", "emoji": "🎈"},
    "heartburn": {"label": "Heartburn / Acidity", "body_part": "abdomen", "emoji": "🔥"},
    "black_stools": {"label": "Black / Tarry Stools", "body_part": "abdomen", "emoji": "🚨"},
    "blood_in_stool": {"label": "Blood in Stool", "body_part": "abdomen", "emoji": "🚨"},
    "loss_of_appetite": {"label": "Loss of Appetite", "body_part": "abdomen", "emoji": "🍽️"},
    "jaundice": {"label": "Yellowing of Skin / Eyes (Jaundice)", "body_part": "abdomen", "emoji": "🟡"},

    # URINARY
    "frequent_urination": {"label": "Frequent Urination", "body_part": "lower", "emoji": "🚽"},
    "painful_urination": {"label": "Painful / Burning Urination", "body_part": "lower", "emoji": "😣"},
    "blood_in_urine": {"label": "Blood in Urine", "body_part": "lower", "emoji": "🚨"},
    "reduced_urination": {"label": "Reduced Urine Output", "body_part": "lower", "emoji": "💧"},
    "dark_urine": {"label": "Dark / Brown Urine", "body_part": "lower", "emoji": "💛"},
    "foamy_urine": {"label": "Foamy Urine", "body_part": "lower", "emoji": "💧"},

    # GENERAL / WHOLE BODY
    "fever": {"label": "Fever", "body_part": "general", "emoji": "🌡️"},
    "high_fever": {"label": "High Fever (above 103°F)", "body_part": "general", "emoji": "🌡️"},
    "fatigue": {"label": "Fatigue / Extreme Tiredness", "body_part": "general", "emoji": "😴"},
    "weakness": {"label": "Weakness / Body Weakness", "body_part": "general", "emoji": "💪"},
    "weight_loss": {"label": "Unexplained Weight Loss", "body_part": "general", "emoji": "⚖️"},
    "weight_gain": {"label": "Unexplained Weight Gain", "body_part": "general", "emoji": "⚖️"},
    "night_sweats": {"label": "Night Sweats", "body_part": "general", "emoji": "💦"},
    "excessive_sweating": {"label": "Excessive Sweating", "body_part": "general", "emoji": "💦"},
    "chills": {"label": "Chills / Shivering", "body_part": "general", "emoji": "🥶"},
    "swollen_lymph_nodes": {"label": "Swollen Lymph Nodes", "body_part": "general", "emoji": "🫀"},
    "pale_skin": {"label": "Pale / Yellowish Skin", "body_part": "general", "emoji": "😶"},
    "rash": {"label": "Skin Rash / Red Spots", "body_part": "general", "emoji": "🔴"},

    # LIMBS & MUSCLES
    "joint_pain": {"label": "Joint Pain", "body_part": "limbs", "emoji": "🦵"},
    "muscle_pain": {"label": "Muscle Pain / Body Aches", "body_part": "limbs", "emoji": "💪"},
    "back_pain": {"label": "Back Pain", "body_part": "lower", "emoji": "🔙"},
    "lower_back_pain": {"label": "Lower Back Pain", "body_part": "lower", "emoji": "🔙"},
    "leg_swelling": {"label": "Leg / Ankle Swelling", "body_part": "limbs", "emoji": "🦵"},
    "numbness": {"label": "Numbness / Tingling in Hands/Feet", "body_part": "limbs", "emoji": "🖐️"},
    "trembling": {"label": "Trembling / Shaking Hands", "body_part": "limbs", "emoji": "🖐️"},

    # HORMONAL / METABOLIC
    "excessive_thirst": {"label": "Excessive Thirst", "body_part": "general", "emoji": "💧"},
    "cold_intolerance": {"label": "Always Feeling Cold", "body_part": "general", "emoji": "🥶"},
    "heat_intolerance": {"label": "Heat Intolerance / Always Feeling Hot", "body_part": "general", "emoji": "🥵"},
    "hair_loss": {"label": "Hair Loss / Thinning", "body_part": "head", "emoji": "💇"},
    "dry_skin": {"label": "Dry / Flaky Skin", "body_part": "general", "emoji": "🧴"},
    "brittle_nails": {"label": "Brittle Nails", "body_part": "limbs", "emoji": "💅"},
    "irregular_periods": {"label": "Irregular Periods", "body_part": "lower", "emoji": "🔴"},
    "mood_changes": {"label": "Mood Swings / Irritability", "body_part": "general", "emoji": "😤"},
    "anxiety": {"label": "Anxiety / Nervousness", "body_part": "general", "emoji": "😰"},
    "depression": {"label": "Depression / Low Mood", "body_part": "general", "emoji": "😢"},
    "insomnia": {"label": "Difficulty Sleeping", "body_part": "general", "emoji": "😶"},
}

# Conditions database with full details
CONDITIONS = {
    "type2_diabetes": {
        "name": "Type 2 Diabetes",
        "emoji": "🍬",
        "category": "Metabolic",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "A chronic condition where blood sugar levels are persistently elevated due to insulin resistance or insufficient insulin production.",
        "specialist": "Endocrinologist / General Physician",
        "specialist_icon": "🏥",
        "key_symptoms": ["excessive_thirst", "frequent_urination", "fatigue", "blurred_vision", "weight_loss", "numbness"],
        "tests": "Fasting Blood Sugar, HbA1c, Post-meal Glucose",
        "action": "Get fasting blood glucose and HbA1c tested immediately. Begin low-carb diet and daily exercise.",
        "red_flags": ["blurred_vision", "numbness", "confusion"],
    },
    "hypothyroidism": {
        "name": "Hypothyroidism",
        "emoji": "🦋",
        "category": "Endocrine",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Underactive thyroid gland producing insufficient thyroid hormone, slowing down metabolism.",
        "specialist": "Endocrinologist / General Physician",
        "specialist_icon": "🏥",
        "key_symptoms": ["fatigue", "weight_gain", "cold_intolerance", "constipation", "hair_loss", "dry_skin", "depression", "memory_loss"],
        "tests": "TSH, Free T4, Free T3, Anti-TPO Antibodies",
        "action": "Get TSH and Free T4 blood test. Highly treatable with daily levothyroxine.",
        "red_flags": [],
    },
    "hyperthyroidism": {
        "name": "Hyperthyroidism",
        "emoji": "🦋",
        "category": "Endocrine",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Overactive thyroid producing excess hormone, speeding up metabolism.",
        "specialist": "Endocrinologist",
        "specialist_icon": "🏥",
        "key_symptoms": ["weight_loss", "palpitations", "excessive_sweating", "heat_intolerance", "anxiety", "trembling", "diarrhea", "insomnia"],
        "tests": "TSH, Free T3, Free T4, TSH Receptor Antibodies",
        "action": "Get thyroid function tests urgently. Antithyroid medication required.",
        "red_flags": ["palpitations", "irregular_heartbeat"],
    },
    "anemia": {
        "name": "Iron Deficiency Anemia",
        "emoji": "🩸",
        "category": "Blood",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Low red blood cell count or hemoglobin due to iron deficiency, reducing oxygen delivery.",
        "specialist": "General Physician / Hematologist",
        "specialist_icon": "🩸",
        "key_symptoms": ["fatigue", "pale_skin", "shortness_of_breath", "dizziness", "weakness", "brittle_nails", "hair_loss", "cold_intolerance"],
        "tests": "CBC (Hemoglobin, Hematocrit), Serum Ferritin, Serum Iron",
        "action": "Get CBC blood test. Start iron-rich diet (spinach, lentils, red meat). Iron supplements if prescribed.",
        "red_flags": ["shortness_of_breath", "palpitations", "fainting"],
    },
    "hypertension": {
        "name": "Hypertension (High Blood Pressure)",
        "emoji": "🫀",
        "category": "Cardiovascular",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Persistently elevated blood pressure that silently damages blood vessels and organs.",
        "specialist": "Cardiologist / General Physician",
        "specialist_icon": "❤️",
        "key_symptoms": ["headache", "dizziness", "blurred_vision", "shortness_of_breath", "chest_pain", "palpitations"],
        "tests": "Blood Pressure Measurement, Kidney Function, ECG, Lipid Profile",
        "action": "Measure BP regularly. Reduce salt, exercise daily. Medication likely needed.",
        "red_flags": ["severe_headache", "chest_pain", "blurred_vision", "confusion"],
    },
    "heart_attack": {
        "name": "Possible Cardiac Event",
        "emoji": "🚨",
        "category": "Cardiovascular",
        "urgency": "emergency",
        "urgency_label": "EMERGENCY — Call Ambulance Now",
        "urgency_color": "red",
        "description": "Combination of symptoms may indicate a heart attack or serious cardiac event requiring immediate emergency care.",
        "specialist": "Emergency Medicine / Cardiologist",
        "specialist_icon": "🚨",
        "key_symptoms": ["chest_pain", "chest_tightness", "shortness_of_breath", "palpitations", "irregular_heartbeat", "fainting", "excessive_sweating"],
        "tests": "ECG, Troponin Blood Test, Echocardiogram (Emergency)",
        "action": "CALL AMBULANCE IMMEDIATELY. Chew aspirin 325mg if available. Do not drive yourself.",
        "red_flags": ["chest_pain", "shortness_of_breath", "fainting"],
    },
    "dengue": {
        "name": "Dengue Fever",
        "emoji": "🦟",
        "category": "Infectious",
        "urgency": "see_doctor_today",
        "urgency_label": "See Doctor Today",
        "urgency_color": "red",
        "description": "Mosquito-borne viral fever causing high fever, severe body pain, and low platelet count.",
        "specialist": "General Physician / Infectious Disease",
        "specialist_icon": "🏥",
        "key_symptoms": ["high_fever", "severe_headache", "muscle_pain", "joint_pain", "rash", "nausea", "fatigue", "chills"],
        "tests": "Dengue NS1 Antigen, Dengue IgM/IgG, CBC (Platelet Count)",
        "action": "See doctor today. Avoid NSAIDs (ibuprofen). Take paracetamol only. Stay hydrated. Hospitalize if platelets drop.",
        "red_flags": ["high_fever", "rash", "vomiting"],
    },
    "uti": {
        "name": "Urinary Tract Infection (UTI)",
        "emoji": "🫘",
        "category": "Urinary",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Bacterial infection in the urinary tract causing painful urination and frequent urge to urinate.",
        "specialist": "General Physician / Urologist",
        "specialist_icon": "🏥",
        "key_symptoms": ["painful_urination", "frequent_urination", "lower_abdominal_pain", "dark_urine", "fever", "blood_in_urine"],
        "tests": "Urine Routine Examination, Urine Culture & Sensitivity",
        "action": "Drink 2-3 liters water daily. Get urine test. Antibiotics prescribed by doctor.",
        "red_flags": ["fever", "blood_in_urine", "lower_back_pain"],
    },
    "kidney_disease": {
        "name": "Kidney Disease / CKD",
        "emoji": "🫘",
        "category": "Urinary",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Gradual loss of kidney function causing fluid retention and waste buildup in the blood.",
        "specialist": "Nephrologist",
        "specialist_icon": "🏥",
        "key_symptoms": ["leg_swelling", "foamy_urine", "reduced_urination", "fatigue", "nausea", "loss_of_appetite", "back_pain", "pale_skin"],
        "tests": "Serum Creatinine, eGFR, Urine Albumin, BUN, Kidney Ultrasound",
        "action": "Get kidney function tests urgently. Control blood sugar and BP. Avoid NSAIDs.",
        "red_flags": ["reduced_urination", "leg_swelling", "confusion"],
    },
    "liver_disease": {
        "name": "Liver Disease / Hepatitis",
        "emoji": "🟤",
        "category": "Digestive",
        "urgency": "see_doctor_today",
        "urgency_label": "See Doctor Today",
        "urgency_color": "red",
        "description": "Liver inflammation or damage affecting bile production and toxin filtering.",
        "specialist": "Gastroenterologist / Hepatologist",
        "specialist_icon": "🏥",
        "key_symptoms": ["jaundice", "dark_urine", "upper_abdominal_pain", "nausea", "fatigue", "loss_of_appetite", "vomiting"],
        "tests": "Liver Function Tests (LFT), Hepatitis B/C serology, Liver Ultrasound",
        "action": "See doctor today. Avoid alcohol completely. Get LFT and hepatitis tests.",
        "red_flags": ["jaundice", "dark_urine", "vomiting"],
    },
    "gerd": {
        "name": "GERD / Acid Reflux",
        "emoji": "🔥",
        "category": "Digestive",
        "urgency": "monitor",
        "urgency_label": "Monitor & Lifestyle Changes",
        "urgency_color": "green",
        "description": "Stomach acid flowing back into the esophagus causing heartburn and discomfort.",
        "specialist": "Gastroenterologist / General Physician",
        "specialist_icon": "🏥",
        "key_symptoms": ["heartburn", "chest_tightness", "nausea", "hoarse_voice", "difficulty_swallowing", "dry_cough", "bloating"],
        "tests": "Usually clinical diagnosis. Endoscopy if symptoms persist.",
        "action": "Avoid spicy/oily food. Don't lie down 2hrs after eating. Elevate bed head. Omeprazole/pantoprazole if prescribed.",
        "red_flags": ["difficulty_swallowing", "coughing_blood", "weight_loss"],
    },
    "asthma": {
        "name": "Asthma / Bronchospasm",
        "emoji": "🫁",
        "category": "Respiratory",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Chronic airway inflammation causing recurrent breathing difficulties and wheezing.",
        "specialist": "Pulmonologist / Allergist",
        "specialist_icon": "🫁",
        "key_symptoms": ["wheezing", "shortness_of_breath", "dry_cough", "chest_tightness", "fatigue"],
        "tests": "Spirometry (Lung Function), Peak Flow, Allergy Tests, Chest X-Ray",
        "action": "Get spirometry done. Use reliever inhaler. Identify and avoid triggers.",
        "red_flags": ["shortness_of_breath", "wheezing", "coughing_blood"],
    },
    "vitamin_d_deficiency": {
        "name": "Vitamin D Deficiency",
        "emoji": "☀️",
        "category": "Nutritional",
        "urgency": "monitor",
        "urgency_label": "Monitor & Supplement",
        "urgency_color": "green",
        "description": "Low Vitamin D causes bone weakness, muscle pain, fatigue, and immune dysfunction.",
        "specialist": "General Physician",
        "specialist_icon": "🏥",
        "key_symptoms": ["fatigue", "bone_pain", "muscle_pain", "depression", "hair_loss", "weakness", "insomnia"],
        "tests": "Serum 25-OH Vitamin D, Calcium, PTH",
        "action": "Get 15-20 mins sunlight daily. Take Vitamin D3 60,000 IU weekly. Recheck after 3 months.",
        "red_flags": [],
    },
    "vitamin_b12_deficiency": {
        "name": "Vitamin B12 Deficiency",
        "emoji": "🔴",
        "category": "Nutritional",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Low B12 causes nerve damage, anemia, and brain function problems — very common in vegetarians.",
        "specialist": "General Physician / Neurologist",
        "specialist_icon": "🏥",
        "key_symptoms": ["numbness", "fatigue", "memory_loss", "depression", "weakness", "pale_skin", "dizziness"],
        "tests": "Serum Vitamin B12, CBC, Homocysteine",
        "action": "Take Methylcobalamin 1500mcg daily. B12 injections if severely deficient. Eat dairy and eggs.",
        "red_flags": ["numbness", "confusion", "memory_loss"],
    },
    "anxiety_disorder": {
        "name": "Anxiety Disorder",
        "emoji": "😰",
        "category": "Mental Health",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Persistent excessive worry and fear causing physical and psychological symptoms.",
        "specialist": "Psychiatrist / Psychologist",
        "specialist_icon": "🧠",
        "key_symptoms": ["anxiety", "palpitations", "shortness_of_breath", "insomnia", "excessive_sweating", "trembling", "dizziness", "chest_tightness"],
        "tests": "Clinical evaluation. Rule out thyroid (TSH) and cardiac causes.",
        "action": "Practice breathing exercises. Consult psychiatrist. Therapy is highly effective.",
        "red_flags": ["fainting", "chest_pain"],
    },
    "depression": {
        "name": "Depression",
        "emoji": "😢",
        "category": "Mental Health",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Persistent low mood, loss of interest, and energy affecting daily life.",
        "specialist": "Psychiatrist / Psychologist",
        "specialist_icon": "🧠",
        "key_symptoms": ["depression", "fatigue", "insomnia", "loss_of_appetite", "weight_loss", "memory_loss", "mood_changes"],
        "tests": "Clinical evaluation. Rule out hypothyroidism (TSH) and Vitamin D / B12 deficiency.",
        "action": "Seek professional counseling. Exercise daily. Ensure adequate Vitamin D and B12.",
        "red_flags": [],
    },
    "gastroenteritis": {
        "name": "Gastroenteritis (Stomach Infection)",
        "emoji": "🦠",
        "category": "Digestive",
        "urgency": "monitor",
        "urgency_label": "Home Care + Monitor",
        "urgency_color": "green",
        "description": "Viral or bacterial stomach infection causing vomiting and diarrhea.",
        "specialist": "General Physician",
        "specialist_icon": "🏥",
        "key_symptoms": ["vomiting", "diarrhea", "nausea", "abdominal_pain", "fever", "weakness", "loss_of_appetite"],
        "tests": "Usually clinical. Stool test if symptoms persist beyond 3 days.",
        "action": "ORS (oral rehydration solution) to prevent dehydration. Bland diet. See doctor if fever persists.",
        "red_flags": ["blood_in_stool", "high_fever", "severe_abdominal_pain"],
    },
    "migraine": {
        "name": "Migraine",
        "emoji": "🤯",
        "category": "Neurological",
        "urgency": "monitor",
        "urgency_label": "Monitor & Manage",
        "urgency_color": "green",
        "description": "Recurring severe headaches often with nausea, vomiting, and sensitivity to light/sound.",
        "specialist": "Neurologist / General Physician",
        "specialist_icon": "🧠",
        "key_symptoms": ["severe_headache", "nausea", "vomiting", "blurred_vision", "dizziness", "mood_changes"],
        "tests": "Clinical diagnosis. MRI if new severe headache pattern.",
        "action": "Rest in dark quiet room. Stay hydrated. Identify triggers (stress, certain foods, sleep deprivation).",
        "red_flags": ["severe_headache", "confusion", "fainting"],
    },
    "pcos": {
        "name": "PCOS (Polycystic Ovary Syndrome)",
        "emoji": "🔴",
        "category": "Hormonal",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Hormonal disorder in women causing irregular periods, excess androgens, and ovarian cysts.",
        "specialist": "Gynecologist / Endocrinologist",
        "specialist_icon": "🏥",
        "key_symptoms": ["irregular_periods", "weight_gain", "hair_loss", "excessive_sweating", "mood_changes", "fatigue", "depression"],
        "tests": "Pelvic Ultrasound, LH/FSH, Testosterone, Fasting Insulin, Blood Sugar",
        "action": "Exercise daily to improve insulin sensitivity. Low-carb diet. Gynecologist evaluation needed.",
        "red_flags": [],
    },
    "appendicitis": {
        "name": "Possible Appendicitis",
        "emoji": "🚨",
        "category": "Surgical Emergency",
        "urgency": "emergency",
        "urgency_label": "EMERGENCY — Go to Hospital Now",
        "urgency_color": "red",
        "description": "Inflammation of the appendix causing severe lower right abdominal pain — surgical emergency.",
        "specialist": "Emergency Surgery",
        "specialist_icon": "🚨",
        "key_symptoms": ["lower_abdominal_pain", "fever", "nausea", "vomiting", "loss_of_appetite"],
        "tests": "Ultrasound Abdomen, CT Scan, Blood Test (WBC)",
        "action": "GO TO HOSPITAL IMMEDIATELY. Do not eat or drink anything. Surgery may be required.",
        "red_flags": ["lower_abdominal_pain", "fever", "vomiting"],
    },
    "stroke": {
        "name": "Possible Stroke / TIA",
        "emoji": "🚨",
        "category": "Neurological Emergency",
        "urgency": "emergency",
        "urgency_label": "EMERGENCY — Call Ambulance Now",
        "urgency_color": "red",
        "description": "Brain attack caused by blocked or burst blood vessel. Time is critical — brain cells die every minute.",
        "specialist": "Emergency Neurology",
        "specialist_icon": "🚨",
        "key_symptoms": ["sudden_weakness", "confusion", "blurred_vision", "severe_headache", "fainting", "numbness"],
        "tests": "CT Scan Brain, MRI Brain (Emergency)",
        "action": "CALL AMBULANCE IMMEDIATELY. Use FAST: Face drooping, Arm weakness, Speech difficulty, Time to call.",
        "red_flags": ["confusion", "fainting", "blurred_vision", "severe_headache"],
    },
    "high_cholesterol": {
        "name": "High Cholesterol / Dyslipidemia",
        "emoji": "🫀",
        "category": "Cardiovascular",
        "urgency": "see_doctor_soon",
        "urgency_label": "See Doctor This Week",
        "urgency_color": "orange",
        "description": "Elevated blood cholesterol levels increasing risk of heart disease and stroke.",
        "specialist": "Cardiologist / General Physician",
        "specialist_icon": "❤️",
        "key_symptoms": ["fatigue", "dizziness", "chest_tightness", "shortness_of_breath"],
        "tests": "Lipid Profile (Total Cholesterol, LDL, HDL, Triglycerides)",
        "action": "Get lipid profile test. Reduce fried food, exercise daily. Statins if LDL above 160.",
        "red_flags": ["chest_pain", "shortness_of_breath"],
    },
}

# Red flag combinations that indicate emergency
RED_FLAG_COMBOS = [
    {
        "symptoms": ["chest_pain", "shortness_of_breath"],
        "warning": "EMERGENCY: Chest pain with breathlessness may indicate a heart attack. Call ambulance immediately!",
        "urgency": "emergency"
    },
    {
        "symptoms": ["chest_pain", "excessive_sweating"],
        "warning": "EMERGENCY: Chest pain with sweating is a classic heart attack sign. Call ambulance immediately!",
        "urgency": "emergency"
    },
    {
        "symptoms": ["severe_headache", "confusion"],
        "warning": "EMERGENCY: Sudden severe headache with confusion may indicate stroke or brain bleed. Call ambulance!",
        "urgency": "emergency"
    },
    {
        "symptoms": ["lower_abdominal_pain", "fever", "vomiting"],
        "warning": "URGENT: This combination may indicate appendicitis. Go to emergency room immediately.",
        "urgency": "emergency"
    },
    {
        "symptoms": ["jaundice", "dark_urine"],
        "warning": "URGENT: Yellow skin/eyes with dark urine indicates serious liver problem. See doctor today.",
        "urgency": "see_doctor_today"
    },
    {
        "symptoms": ["coughing_blood"],
        "warning": "URGENT: Coughing blood requires immediate medical evaluation.",
        "urgency": "emergency"
    },
    {
        "symptoms": ["blood_in_stool", "black_stools"],
        "warning": "URGENT: Blood in stool or black stools may indicate internal bleeding. See doctor today.",
        "urgency": "see_doctor_today"
    },
]

# Specialist guide
SPECIALISTS = {
    "Cardiologist": {"icon": "❤️", "treats": "Heart disease, hypertension, cholesterol, chest pain"},
    "Endocrinologist": {"icon": "🦋", "treats": "Diabetes, thyroid disorders, hormonal conditions"},
    "Nephrologist": {"icon": "🫘", "treats": "Kidney disease, kidney stones, high creatinine"},
    "Gastroenterologist": {"icon": "🟤", "treats": "Liver, stomach, intestinal conditions, GERD"},
    "Pulmonologist": {"icon": "🫁", "treats": "Asthma, lung disease, breathing problems"},
    "Neurologist": {"icon": "🧠", "treats": "Headache, migraine, nerve problems, memory issues"},
    "Hematologist": {"icon": "🩸", "treats": "Blood disorders, anemia, platelet problems"},
    "Gynecologist": {"icon": "🔴", "treats": "PCOS, menstrual issues, hormonal conditions in women"},
    "Psychiatrist": {"icon": "😊", "treats": "Depression, anxiety, mental health conditions"},
    "General Physician": {"icon": "🏥", "treats": "First consultation for all conditions"},
}
