# wiki/knowledge_data.py
# Complete offline medical wiki knowledge base

CATEGORIES = [
    {"name": "Heart & Blood Vessels", "slug": "cardiovascular", "icon": "🫀", "order": 1, "description": "Conditions affecting the heart and circulatory system"},
    {"name": "Blood Disorders", "slug": "blood", "icon": "🩸", "order": 2, "description": "Conditions affecting blood cells and clotting"},
    {"name": "Diabetes & Metabolism", "slug": "diabetes", "icon": "🍬", "order": 3, "description": "Blood sugar, insulin, and metabolic conditions"},
    {"name": "Thyroid & Hormones", "slug": "thyroid", "icon": "🦋", "order": 4, "description": "Thyroid gland and hormonal disorders"},
    {"name": "Kidneys & Urinary", "slug": "kidney", "icon": "🫘", "order": 5, "description": "Kidney function and urinary tract conditions"},
    {"name": "Liver & Digestive", "slug": "liver", "icon": "🟤", "order": 6, "description": "Liver function and digestive system"},
    {"name": "Respiratory", "slug": "respiratory", "icon": "🫁", "order": 7, "description": "Lungs and breathing disorders"},
    {"name": "Bones & Joints", "slug": "bones", "icon": "🦴", "order": 8, "description": "Bone density, arthritis, and joint conditions"},
    {"name": "Mental Health", "slug": "mental", "icon": "🧠", "order": 9, "description": "Mental and neurological health conditions"},
    {"name": "Medical Terms", "slug": "terms", "icon": "📖", "order": 10, "description": "Common medical terminology explained"},
    {"name": "Medications & Drugs", "slug": "drugs", "icon": "💊", "order": 11, "description": "Common medications and how they work"},
    {"name": "Vitamins & Nutrition", "slug": "nutrition", "icon": "🥗", "order": 12, "description": "Vitamins, minerals, and nutritional health"},
]

ARTICLES = [

    # ══════════════════════════════════════════
    # CARDIOVASCULAR
    # ══════════════════════════════════════════
    {
        "title": "Hypertension (High Blood Pressure)",
        "slug": "hypertension",
        "type": "disease",
        "category": "cardiovascular",
        "icon": "🫀",
        "featured": True,
        "tags": "blood pressure, heart, stroke, kidney",
        "overview": "Hypertension is a chronic condition where the force of blood against artery walls is consistently too high (≥130/80 mmHg). It is called the 'silent killer' because it often has no symptoms but significantly increases risk of heart attack, stroke, and kidney failure. It affects over 1.3 billion people worldwide.",
        "symptoms": "• Usually no symptoms (silent killer)\n• Headache (especially in the morning)\n• Dizziness or lightheadedness\n• Blurred or double vision\n• Shortness of breath\n• Nosebleeds\n• Chest pain or tightness\n• Blood in urine (in severe cases)",
        "causes": "• Primary (essential) hypertension: No known single cause; develops over years\n• Secondary hypertension causes:\n  - Kidney disease\n  - Thyroid disorders\n  - Sleep apnea\n  - Adrenal gland tumors\n  - Certain medications (birth control pills, NSAIDs)",
        "risk_factors": "• Age over 55\n• Family history of hypertension\n• Obesity or overweight\n• Physical inactivity\n• High salt intake\n• Heavy alcohol consumption\n• Smoking\n• Chronic stress\n• Diabetes",
        "treatments": "• Lifestyle modifications (first-line treatment)\n• ACE inhibitors (e.g., Enalapril, Lisinopril)\n• ARBs (e.g., Losartan, Valsartan)\n• Beta-blockers (e.g., Atenolol, Metoprolol)\n• Calcium channel blockers (e.g., Amlodipine)\n• Diuretics (e.g., Hydrochlorothiazide)\n• Regular blood pressure monitoring",
        "medications": "• Amlodipine 5-10mg daily — calcium channel blocker\n• Losartan 50-100mg daily — ARB\n• Enalapril 5-40mg daily — ACE inhibitor\n• Atenolol 25-100mg daily — beta blocker\n• Hydrochlorothiazide 12.5-25mg — diuretic",
        "prevention": "• Maintain healthy weight (BMI 18.5-24.9)\n• Exercise 150 minutes per week\n• DASH diet (low sodium, high potassium)\n• Limit salt to less than 2300mg/day\n• Quit smoking\n• Limit alcohol to 1-2 drinks/day\n• Manage stress through meditation, yoga\n• Regular blood pressure checks",
        "lifestyle_tips": "• Monitor BP at home daily, same time each morning\n• Eat more bananas, spinach, beans (high potassium)\n• Reduce processed and packaged foods\n• Walk 30 minutes daily\n• Avoid caffeine before BP measurement\n• Get 7-8 hours of quality sleep\n• Practice deep breathing exercises",
        "when_to_see_doctor": "• BP consistently above 140/90\n• Severe headache with vision changes\n• Chest pain or shortness of breath\n• Sudden weakness or numbness (stroke signs)\n• Blood in urine",
        "related_tests": "Blood pressure measurement, Kidney function tests, ECG, Echocardiogram, Blood glucose, Lipid profile",
    },

    {
        "title": "High Cholesterol (Hypercholesterolemia)",
        "slug": "high-cholesterol",
        "type": "disease",
        "category": "cardiovascular",
        "icon": "🫀",
        "featured": True,
        "tags": "cholesterol, ldl, hdl, lipid, heart",
        "overview": "High cholesterol means too much LDL (bad) cholesterol in the blood, which builds up as plaques in artery walls. This narrows arteries (atherosclerosis) and can lead to heart attack or stroke. Total cholesterol above 200 mg/dL, LDL above 100 mg/dL, or HDL below 40 mg/dL are concerning.",
        "symptoms": "• Usually no symptoms until a heart attack or stroke occurs\n• In severe cases: xanthomas (yellowish fat deposits under skin)\n• Corneal arcus (grey ring around the eye) in younger patients\n• Xanthelasma (yellowish patches around eyelids)",
        "causes": "• Unhealthy diet high in saturated and trans fats\n• Physical inactivity\n• Obesity\n• Smoking\n• Genetics (familial hypercholesterolemia)\n• Diabetes\n• Hypothyroidism\n• Kidney disease\n• Certain medications (steroids, beta-blockers)",
        "risk_factors": "• Age (men >45, women >55)\n• Family history\n• High-fat diet\n• Smoking\n• Obesity\n• Diabetes\n• Sedentary lifestyle",
        "treatments": "• Diet and lifestyle changes\n• Statins (most effective medication class)\n• Ezetimibe\n• PCSK9 inhibitors (for severe cases)\n• Bile acid sequestrants\n• Niacin (vitamin B3 in high doses)",
        "medications": "• Atorvastatin 10-80mg — most prescribed statin\n• Rosuvastatin 5-40mg — potent LDL-lowering\n• Ezetimibe 10mg — reduces gut absorption\n• Fenofibrate — mainly for high triglycerides\n• Fish oil (Omega-3) 1-4g/day — lowers triglycerides",
        "prevention": "• Heart-healthy diet: oats, nuts, fish, olive oil\n• Exercise 30 minutes daily\n• Quit smoking\n• Maintain healthy weight\n• Limit saturated fats (red meat, butter, cheese)\n• Eliminate trans fats (fried foods, margarine)\n• Annual lipid profile testing after age 35",
        "lifestyle_tips": "• Add oats to breakfast — beta-glucan lowers LDL\n• Eat fatty fish (salmon, mackerel) twice a week\n• Use olive oil instead of butter\n• Eat a handful of nuts daily\n• Increase fruits and vegetables\n• Avoid fast food and processed snacks\n• Cycle or walk instead of driving short distances",
        "when_to_see_doctor": "• Total cholesterol above 240 mg/dL\n• LDL above 160 mg/dL\n• Family history of heart disease before age 50\n• Chest pain or shortness of breath\n• Diabetes with any cholesterol abnormality",
        "related_tests": "Lipid profile (Total cholesterol, LDL, HDL, Triglycerides), Blood glucose, Thyroid function, Kidney function",
    },

    {
        "title": "Heart Attack (Myocardial Infarction)",
        "slug": "heart-attack",
        "type": "disease",
        "category": "cardiovascular",
        "icon": "🚨",
        "featured": False,
        "tags": "heart attack, chest pain, cardiac, emergency",
        "overview": "A heart attack occurs when blood flow to a part of the heart is blocked, usually by a blood clot forming on a cholesterol plaque. Heart muscle begins to die without oxygen. It is a medical emergency — every minute without treatment causes more damage. Over 17 million people die from cardiovascular disease annually.",
        "symptoms": "• Crushing chest pain or pressure (most common)\n• Pain radiating to left arm, jaw, neck, or back\n• Shortness of breath\n• Cold sweat\n• Nausea or vomiting\n• Lightheadedness or fainting\n• Unusual fatigue (especially in women)\n• Women may have atypical symptoms: jaw pain, fatigue, nausea without chest pain",
        "causes": "• Coronary artery disease (blocked arteries)\n• Blood clot formation on cholesterol plaque\n• Coronary artery spasm (less common)\n• Severe stress (Takotsubo cardiomyopathy)",
        "risk_factors": "• High cholesterol\n• Hypertension\n• Diabetes\n• Smoking\n• Obesity\n• Physical inactivity\n• Family history\n• Age (men >45, women >55)\n• Stress",
        "treatments": "• EMERGENCY: Call ambulance immediately\n• Aspirin 325mg (chew immediately if available)\n• Angioplasty (PCI) — gold standard treatment\n• Thrombolytic therapy (clot-busting drugs)\n• Coronary artery bypass surgery (CABG)\n• Post-attack: statins, aspirin, beta-blockers lifelong",
        "medications": "• Aspirin — prevents further clotting\n• Clopidogrel — antiplatelet\n• Atorvastatin — reduces cholesterol\n• Metoprolol — protects heart muscle\n• ACE inhibitors — reduces heart workload",
        "prevention": "• Control cholesterol, BP, and blood sugar\n• Quit smoking — single most important step\n• Exercise regularly\n• Maintain healthy weight\n• Eat heart-healthy diet\n• Manage stress\n• Regular cardiac checkups after age 40",
        "lifestyle_tips": "• Know the warning signs — act fast, every minute matters\n• Keep an aspirin accessible if at high risk\n• Do cardiac rehabilitation after a heart attack\n• Mediterranean diet reduces recurrence risk\n• Avoid extreme cold or heat exertion",
        "when_to_see_doctor": "• ANY chest pain — call emergency services immediately\n• Sudden shortness of breath\n• Pain radiating to arm or jaw\n• Cold sweat with nausea",
        "related_tests": "ECG, Troponin blood test, Echocardiogram, Coronary angiography, Lipid profile, Blood glucose",
    },

    # ══════════════════════════════════════════
    # BLOOD DISORDERS
    # ══════════════════════════════════════════
    {
        "title": "Anemia (Iron Deficiency)",
        "slug": "anemia-iron-deficiency",
        "type": "disease",
        "category": "blood",
        "icon": "🩸",
        "featured": True,
        "tags": "anemia, hemoglobin, iron, fatigue, blood",
        "overview": "Iron deficiency anemia is the most common nutritional deficiency worldwide, affecting over 2 billion people. It occurs when the body lacks enough iron to produce sufficient hemoglobin — the protein in red blood cells that carries oxygen. Hemoglobin below 12 g/dL in women or 13.5 g/dL in men indicates anemia.",
        "symptoms": "• Persistent fatigue and weakness\n• Pale or yellowish skin\n• Shortness of breath on exertion\n• Dizziness or lightheadedness\n• Cold hands and feet\n• Brittle nails\n• Hair loss\n• Rapid or irregular heartbeat\n• Headaches\n• Unusual cravings (ice, dirt) — called pica",
        "causes": "• Inadequate iron intake (vegetarian/vegan diet)\n• Poor iron absorption (celiac disease, gastric surgery)\n• Blood loss (heavy periods, ulcers, colon polyps)\n• Pregnancy (increased iron demand)\n• Frequent blood donation",
        "risk_factors": "• Women of reproductive age (monthly blood loss)\n• Pregnant women\n• Infants and young children (rapid growth)\n• Vegetarians and vegans\n• Frequent blood donors\n• People with GI disorders",
        "treatments": "• Oral iron supplements (ferrous sulfate, ferrous gluconate)\n• Vitamin C with iron for better absorption\n• Dietary changes\n• Treat underlying cause (e.g., stop bleeding)\n• IV iron infusion (if oral iron not tolerated)\n• Blood transfusion (severe cases)",
        "medications": "• Ferrous Sulfate 325mg — most common iron supplement\n• Ferrous Gluconate — gentler on stomach\n• Ferric carboxymaltose — IV iron\n• Folic acid — if folate deficiency co-exists\n• Vitamin B12 — if B12 deficiency",
        "prevention": "• Eat iron-rich foods daily: red meat, spinach, lentils, beans\n• Combine iron foods with Vitamin C (lemon juice)\n• Avoid tea/coffee with meals (inhibits absorption)\n• Cook in cast iron cookware\n• Regular hemoglobin checks during pregnancy",
        "lifestyle_tips": "• Eat spinach, lentils, chickpeas, pumpkin seeds daily\n• Add lemon juice to iron-rich meals\n• Avoid tea or coffee within 1 hour of meals\n• Pomegranate juice is a good natural iron source\n• Soaking and sprouting legumes improves iron absorption\n• Rest adequately — anemia causes fatigue",
        "when_to_see_doctor": "• Extreme fatigue affecting daily activities\n• Hemoglobin below 10 g/dL\n• Shortness of breath at rest\n• Heart palpitations\n• Suspected internal bleeding (black stools)",
        "related_tests": "CBC (Hemoglobin, Hematocrit), Serum ferritin, Serum iron, TIBC, Peripheral blood smear, Vitamin B12",
    },

    {
        "title": "Thrombocytopenia (Low Platelet Count)",
        "slug": "thrombocytopenia",
        "type": "disease",
        "category": "blood",
        "icon": "🩸",
        "featured": False,
        "tags": "platelets, bleeding, dengue, blood clotting",
        "overview": "Thrombocytopenia is a condition where platelet count falls below 150,000 cells/µL. Platelets are essential for blood clotting. Low platelets can cause excessive bleeding from minor injuries or spontaneous bleeding. It can be caused by infections like dengue fever, autoimmune conditions, medications, or bone marrow disorders.",
        "symptoms": "• Easy bruising\n• Prolonged bleeding from cuts\n• Petechiae (tiny red/purple spots on skin)\n• Purpura (larger purple patches)\n• Bleeding gums or nose\n• Blood in urine or stools\n• Heavy menstrual periods\n• Fatigue",
        "causes": "• Dengue fever (very common in India)\n• Viral infections (HIV, hepatitis C)\n• Autoimmune disorders (ITP)\n• Medications (heparin, quinine, some antibiotics)\n• Chemotherapy\n• Bone marrow disorders\n• Alcohol abuse\n• Severe bacterial infections (sepsis)",
        "risk_factors": "• Living in dengue-endemic areas\n• Autoimmune conditions\n• HIV infection\n• Excessive alcohol use\n• Certain medications",
        "treatments": "• Treat underlying cause\n• Corticosteroids for ITP\n• IVIG (intravenous immunoglobulin)\n• Platelet transfusion (count below 10,000)\n• Thrombopoietin receptor agonists\n• Splenectomy (last resort for chronic ITP)",
        "medications": "• Prednisolone — first-line for ITP\n• Eltrombopag — stimulates platelet production\n• Romiplostim — TPO receptor agonist\n• Dexamethasone — for acute episodes",
        "prevention": "• Prevent dengue: eliminate mosquito breeding sites, use repellent\n• Avoid medications that lower platelets unless necessary\n• Limit alcohol consumption\n• Protect against HIV and hepatitis C",
        "lifestyle_tips": "• Avoid contact sports or activities that risk injury\n• Use soft toothbrush to prevent gum bleeding\n• Eat papaya, pomegranate, pumpkin — may help raise platelets\n• Avoid aspirin and NSAIDs completely\n• Wear protective gear during activities\n• Monitor for petechiae (tiny red spots on skin)",
        "when_to_see_doctor": "• Platelet count below 100,000\n• Unexplained bruising or petechiae\n• Prolonged bleeding from minor cuts\n• Blood in urine or black stools\n• Sudden severe headache (possible brain bleed)",
        "related_tests": "CBC with platelet count, Peripheral smear, Dengue NS1/IgM/IgG, HIV test, Bone marrow biopsy (if needed)",
    },

    # ══════════════════════════════════════════
    # DIABETES
    # ══════════════════════════════════════════
    {
        "title": "Type 2 Diabetes",
        "slug": "type-2-diabetes",
        "type": "disease",
        "category": "diabetes",
        "icon": "🍬",
        "featured": True,
        "tags": "diabetes, blood sugar, insulin, glucose, HbA1c",
        "overview": "Type 2 diabetes is a chronic condition where the body either doesn't produce enough insulin or doesn't use insulin effectively, resulting in high blood glucose. It accounts for 90-95% of all diabetes cases. India has over 77 million diabetics — the second highest in the world. Fasting glucose above 126 mg/dL or HbA1c above 6.5% confirms diagnosis.",
        "symptoms": "• Increased thirst (polydipsia)\n• Frequent urination (polyuria)\n• Unusual hunger\n• Unexplained weight loss\n• Fatigue\n• Blurred vision\n• Slow-healing wounds\n• Frequent infections\n• Numbness or tingling in hands/feet\n• Dark skin patches (acanthosis nigricans)",
        "causes": "• Insulin resistance — cells don't respond to insulin\n• Insufficient insulin production\n• Excess body fat (especially abdominal)\n• Physical inactivity\n• Genetics",
        "risk_factors": "• Overweight or obesity (BMI >25)\n• Abdominal obesity (waist >90cm men, >80cm women)\n• Physical inactivity\n• Family history\n• Age above 45\n• Prediabetes (fasting glucose 100-125)\n• Gestational diabetes history\n• PCOS\n• High-carb, high-sugar diet",
        "treatments": "• Lifestyle modification (first and most important)\n• Metformin (first-line medication)\n• SGLT2 inhibitors (Dapagliflozin, Empagliflozin)\n• GLP-1 agonists (Semaglutide, Liraglutide)\n• DPP-4 inhibitors (Sitagliptin)\n• Sulfonylureas (Glimepiride, Glipizide)\n• Insulin therapy (when other medications insufficient)",
        "medications": "• Metformin 500-2000mg — reduces glucose production\n• Glimepiride 1-4mg — stimulates insulin release\n• Sitagliptin 100mg — DPP-4 inhibitor\n• Dapagliflozin 10mg — removes glucose in urine\n• Insulin (various types) — when oral medications fail",
        "prevention": "• Achieve and maintain healthy weight\n• 150 minutes of moderate exercise per week\n• Low glycemic index diet\n• Reduce refined sugars and carbohydrates\n• Annual blood sugar screening after age 35\n• Manage prediabetes aggressively",
        "lifestyle_tips": "• Walk 30-45 minutes after every meal\n• Eat small, frequent meals (every 3-4 hours)\n• Avoid white rice, maida, sugar, soft drinks\n• Choose brown rice, whole wheat, oats instead\n• Monitor blood sugar daily with glucometer\n• Keep feet clean and inspect daily for wounds\n• Carry glucose tablets for hypoglycemia emergencies\n• HbA1c target: below 7.0%",
        "when_to_see_doctor": "• Fasting glucose above 126 mg/dL\n• HbA1c above 6.5%\n• Severe fatigue with excessive thirst\n• Foot wounds not healing\n• Vision changes\n• Chest pain (diabetes increases heart risk)",
        "related_tests": "Fasting blood glucose, HbA1c, Post-meal glucose, Kidney function, Lipid profile, Urine microalbumin, Eye examination",
    },

    {
        "title": "Prediabetes",
        "slug": "prediabetes",
        "type": "disease",
        "category": "diabetes",
        "icon": "⚠️",
        "featured": False,
        "tags": "prediabetes, blood sugar, prevention, glucose",
        "overview": "Prediabetes is a condition where blood sugar levels are higher than normal but not yet high enough to be classified as Type 2 diabetes. Fasting glucose between 100-125 mg/dL or HbA1c between 5.7-6.4% indicates prediabetes. It is a critical warning stage — up to 70% of people with prediabetes will develop Type 2 diabetes if no action is taken, but it is fully reversible with lifestyle changes.",
        "symptoms": "• Often no symptoms\n• Increased thirst\n• Frequent urination\n• Fatigue\n• Darkened skin in armpits or neck (acanthosis nigricans)",
        "causes": "• Insulin resistance\n• Excess abdominal fat\n• Physical inactivity\n• High-sugar, high-carb diet\n• Genetics",
        "risk_factors": "• Overweight\n• Age above 45\n• Family history of diabetes\n• Sedentary lifestyle\n• High-carb diet\n• History of gestational diabetes",
        "treatments": "• Lifestyle change is the most effective treatment\n• Metformin (for high-risk individuals)\n• Weight loss program\n• Diabetes Prevention Program (DPP)",
        "medications": "• Metformin 500-1000mg — for high-risk prediabetics\n• Not usually required if lifestyle changes are made",
        "prevention": "• Lose 5-7% of body weight\n• Exercise 150 minutes per week\n• Low-sugar, low-refined-carb diet\n• Regular blood sugar monitoring",
        "lifestyle_tips": "• Even losing 5kg can reverse prediabetes\n• Walk 30 minutes daily — most effective intervention\n• Replace white rice with cauliflower rice or brown rice\n• Eat more fiber: vegetables, legumes, whole grains\n• Avoid fruit juices — eat whole fruits instead\n• Sleep 7-8 hours (poor sleep worsens insulin resistance)",
        "when_to_see_doctor": "• Fasting glucose above 100 mg/dL\n• HbA1c above 5.7%\n• Strong family history + any symptoms",
        "related_tests": "Fasting glucose, HbA1c, 2-hour glucose tolerance test, Fasting insulin, Lipid profile",
    },

    # ══════════════════════════════════════════
    # THYROID
    # ══════════════════════════════════════════
    {
        "title": "Hypothyroidism (Underactive Thyroid)",
        "slug": "hypothyroidism",
        "type": "disease",
        "category": "thyroid",
        "icon": "🦋",
        "featured": True,
        "tags": "thyroid, TSH, levothyroxine, fatigue, weight gain",
        "overview": "Hypothyroidism occurs when the thyroid gland doesn't produce enough thyroid hormone, slowing down metabolism. TSH above 4.0 µIU/mL (with low T4) confirms the diagnosis. It affects about 5% of the population, especially women over 60. Hashimoto's thyroiditis is the most common cause. With proper medication, hypothyroidism is highly manageable.",
        "symptoms": "• Fatigue and sluggishness\n• Weight gain despite normal eating\n• Feeling cold all the time\n• Constipation\n• Dry skin and hair\n• Hair thinning or loss\n• Slow heart rate\n• Depression\n• Memory problems (brain fog)\n• Puffy face and swollen ankles\n• Heavy or irregular periods\n• Muscle aches and weakness",
        "causes": "• Hashimoto's thyroiditis (autoimmune — most common)\n• Previous thyroid surgery\n• Radiation therapy to the neck\n• Iodine deficiency (common in India)\n• Certain medications (lithium, amiodarone)\n• Congenital hypothyroidism",
        "risk_factors": "• Female gender (5-8x more common in women)\n• Age over 60\n• Family history of thyroid disease\n• Autoimmune conditions (Type 1 diabetes, rheumatoid arthritis)\n• Previous thyroid problems\n• Iodine-deficient diet",
        "treatments": "• Levothyroxine (T4 hormone replacement) — lifelong\n• Regular TSH monitoring every 6-12 months\n• Dose adjustment based on TSH levels\n• Treating underlying cause if possible",
        "medications": "• Levothyroxine (25-200mcg) — standard treatment, taken daily on empty stomach\n• Liothyronine (T3) — added in some cases\n• Note: Take 30-60 minutes before breakfast for best absorption",
        "prevention": "• Adequate iodine intake (use iodized salt)\n• Selenium-rich foods (Brazil nuts, tuna, eggs)\n• Regular thyroid screening for high-risk groups\n• Avoid excessive soy consumption (may interfere with thyroid)",
        "lifestyle_tips": "• Take levothyroxine same time every morning, on empty stomach\n• Wait 30-60 minutes before eating or drinking anything other than water\n• Calcium, iron, and antacids should be taken 4 hours apart from levothyroxine\n• Eat selenium-rich foods: Brazil nuts (1-2 per day), tuna, eggs\n• Use iodized salt in cooking\n• Regular exercise helps combat fatigue and weight gain\n• Get 8 hours of sleep\n• Monitor weight weekly — unexplained gain may indicate dose adjustment needed",
        "when_to_see_doctor": "• TSH above 4.0 with symptoms\n• Extreme fatigue affecting daily life\n• Unexplained weight gain of 5+ kg\n• Depression or severe memory problems\n• Pregnant women with any thyroid abnormality",
        "related_tests": "TSH, Free T4, Free T3, Anti-TPO antibodies, Thyroid ultrasound",
    },

    {
        "title": "Hyperthyroidism (Overactive Thyroid)",
        "slug": "hyperthyroidism",
        "type": "disease",
        "category": "thyroid",
        "icon": "🦋",
        "featured": False,
        "tags": "thyroid, TSH, Graves disease, palpitations, weight loss",
        "overview": "Hyperthyroidism occurs when the thyroid produces too much hormone, speeding up metabolism. TSH below 0.4 µIU/mL (with high T3/T4) indicates hyperthyroidism. Graves' disease (autoimmune) is the most common cause. Symptoms are the opposite of hypothyroidism — weight loss, rapid heartbeat, anxiety, and heat intolerance.",
        "symptoms": "• Unexplained weight loss\n• Rapid or irregular heartbeat (palpitations)\n• Increased appetite\n• Nervousness, anxiety, irritability\n• Trembling hands\n• Sweating and heat intolerance\n• Frequent bowel movements\n• Fatigue and muscle weakness\n• Difficulty sleeping\n• Bulging eyes (exophthalmos — in Graves' disease)\n• Enlarged thyroid (goiter)",
        "causes": "• Graves' disease (autoimmune — most common, 70-80%)\n• Toxic multinodular goiter\n• Thyroid nodule (adenoma)\n• Thyroiditis (inflammation)\n• Excessive iodine intake\n• Over-replacement of thyroid medication",
        "risk_factors": "• Female gender\n• Age 20-40 years\n• Family history of thyroid disease\n• Autoimmune conditions\n• Pregnancy\n• Stress",
        "treatments": "• Antithyroid medications (Methimazole, Propylthiouracil)\n• Radioactive iodine therapy\n• Beta-blockers (for symptom control)\n• Surgery (thyroidectomy — for large goiter)\n• Monitoring every 3-6 months",
        "medications": "• Methimazole 5-30mg — blocks thyroid hormone production\n• Propylthiouracil (PTU) — used in pregnancy\n• Propranolol 10-40mg — controls heart rate and tremors\n• Atenolol — alternative beta-blocker",
        "prevention": "• No guaranteed prevention for Graves' disease\n• Avoid excess iodine supplements\n• Regular thyroid screening\n• Manage stress",
        "lifestyle_tips": "• Avoid caffeine and stimulants — worsen palpitations\n• Eat calcium-rich foods — hyperthyroidism weakens bones\n• Avoid excess iodine (seaweed, iodine supplements)\n• Cool environment helps with heat intolerance\n• Gentle exercise only — heart rate is already elevated\n• Protect eyes if you have Graves' ophthalmopathy",
        "when_to_see_doctor": "• Rapid heartbeat or irregular rhythm\n• Unexplained weight loss\n• Bulging eyes\n• Severe anxiety or tremors\n• Thyroid storm (rare emergency): fever, extreme heart rate",
        "related_tests": "TSH, Free T3, Free T4, TSH receptor antibodies (TRAb), Thyroid scan, Thyroid ultrasound",
    },

    # ══════════════════════════════════════════
    # KIDNEY
    # ══════════════════════════════════════════
    {
        "title": "Chronic Kidney Disease (CKD)",
        "slug": "chronic-kidney-disease",
        "type": "disease",
        "category": "kidney",
        "icon": "🫘",
        "featured": True,
        "tags": "kidney, creatinine, GFR, renal failure, dialysis",
        "overview": "Chronic Kidney Disease is the gradual loss of kidney function over months or years. Kidneys filter waste and excess fluid from blood. CKD is staged 1-5 based on GFR (glomerular filtration rate). Diabetes and hypertension cause 60-70% of CKD cases. Creatinine above 1.2 mg/dL in men or 1.0 in women may indicate reduced kidney function.",
        "symptoms": "• Early stages: usually no symptoms\n• Fatigue and weakness\n• Reduced urine output\n• Swelling in ankles, feet, or face\n• Shortness of breath\n• Nausea and vomiting\n• Loss of appetite\n• Mental confusion\n• Muscle cramps\n• Itchy skin\n• Foamy or bloody urine",
        "causes": "• Diabetes (most common cause)\n• Hypertension (second most common)\n• Glomerulonephritis (kidney inflammation)\n• Polycystic kidney disease (genetic)\n• Recurrent kidney infections\n• NSAIDs overuse (ibuprofen, diclofenac)\n• Contrast dye (from CT scans)",
        "risk_factors": "• Diabetes\n• High blood pressure\n• Heart disease\n• Obesity\n• Smoking\n• Family history of kidney disease\n• Age over 60\n• Frequent NSAID use",
        "treatments": "• Control blood pressure (target <130/80)\n• Control blood sugar (HbA1c <7%)\n• ACE inhibitors or ARBs (protect kidneys)\n• Low protein diet\n• Avoid nephrotoxic drugs (NSAIDs, contrast)\n• Treat anemia (erythropoietin injections)\n• Dialysis (Stage 5 CKD)\n• Kidney transplant",
        "medications": "• Enalapril/Lisinopril — ACE inhibitors, protect kidneys\n• Losartan/Valsartan — ARBs, alternative to ACE inhibitors\n• Furosemide — for fluid retention\n• Erythropoietin — for CKD anemia\n• Calcium carbonate — for phosphate control",
        "prevention": "• Control diabetes and blood pressure aggressively\n• Stay well hydrated (2-3 liters water/day)\n• Avoid NSAIDs (ibuprofen) for pain — use paracetamol instead\n• Annual kidney function tests if diabetic or hypertensive\n• Avoid contrast dye if GFR is low\n• Quit smoking\n• Maintain healthy weight",
        "lifestyle_tips": "• Limit salt to less than 2g/day\n• Reduce protein (especially red meat)\n• Avoid potassium-rich foods if GFR is very low (bananas, oranges)\n• Avoid phosphorus-rich foods (dairy, nuts, cola)\n• Track daily fluid intake\n• Weigh yourself daily — sudden gain means fluid retention\n• Take all medications as prescribed\n• Never take herbal remedies without doctor approval",
        "when_to_see_doctor": "• Creatinine above 1.5 mg/dL\n• Reduced urine output\n• Swelling in legs or face\n• Foamy urine\n• Diabetic or hypertensive with no annual kidney check",
        "related_tests": "Serum creatinine, eGFR, BUN, Urine albumin-to-creatinine ratio, Kidney ultrasound, Electrolytes (sodium, potassium)",
    },

    {
        "title": "Urinary Tract Infection (UTI)",
        "slug": "uti",
        "type": "disease",
        "category": "kidney",
        "icon": "🫘",
        "featured": False,
        "tags": "UTI, urine infection, bladder, bacteria",
        "overview": "A UTI is an infection in any part of the urinary system — kidneys, ureters, bladder, or urethra. Most infections involve the lower urinary tract (bladder and urethra). Women are more prone due to shorter urethra. E. coli bacteria cause 80-85% of UTIs. If untreated, it can spread to kidneys (pyelonephritis).",
        "symptoms": "• Burning or painful urination\n• Frequent urge to urinate (little urine comes out)\n• Cloudy, dark, or foul-smelling urine\n• Pink or reddish urine (blood in urine)\n• Pelvic pain or pressure\n• Fever and chills (if kidney involved)\n• Nausea and vomiting (kidney infection)\n• Back or flank pain (kidney infection)",
        "causes": "• E. coli bacteria (most common)\n• Staphylococcus saprophyticus\n• Klebsiella, Proteus, Enterococcus\n• Catheter use\n• Sexual activity\n• Menopause (reduced estrogen changes vaginal flora)",
        "risk_factors": "• Female gender\n• Sexual activity\n• Urinary catheter\n• Urinary tract abnormalities\n• Diabetes\n• Weakened immune system\n• Menopause\n• Kidney stones",
        "treatments": "• Antibiotics (3-7 day course)\n• Increased water intake\n• Pain relief (phenazopyridine)\n• Hospitalization for severe kidney infection",
        "medications": "• Nitrofurantoin 100mg — for uncomplicated UTI\n• Trimethoprim-sulfamethoxazole — common antibiotic\n• Ciprofloxacin 500mg — for complicated UTI\n• Phenazopyridine — relieves pain and burning (not antibiotic)",
        "prevention": "• Drink 2-3 liters of water daily\n• Urinate after sexual intercourse\n• Wipe front to back\n• Avoid holding urine for long periods\n• Cranberry juice or D-mannose (may reduce recurrence)\n• Cotton underwear\n• Avoid scented feminine products",
        "lifestyle_tips": "• Drink water throughout the day — dilutes bacteria\n• Urinate every 3-4 hours, don't hold it\n• Drink unsweetened cranberry juice\n• Complete full antibiotic course even if feeling better\n• Avoid bubble baths and harsh soaps\n• Change sanitary pads frequently during periods",
        "when_to_see_doctor": "• Fever with UTI symptoms (kidney infection)\n• Symptoms not improving after 2 days of antibiotics\n• Blood in urine\n• Recurrent UTIs (3+ per year)\n• UTI in men (always needs evaluation)\n• UTI in pregnant women",
        "related_tests": "Urine routine examination, Urine culture and sensitivity, Blood culture (if fever), Kidney ultrasound (recurrent cases)",
    },

    # ══════════════════════════════════════════
    # RESPIRATORY
    # ══════════════════════════════════════════
    {
        "title": "Asthma",
        "slug": "asthma",
        "type": "disease",
        "category": "respiratory",
        "icon": "🫁",
        "featured": False,
        "tags": "asthma, breathing, inhaler, wheeze, bronchospasm",
        "overview": "Asthma is a chronic inflammatory disease of the airways that causes recurrent episodes of wheezing, breathlessness, chest tightness, and coughing. Airways become swollen and narrow, and extra mucus is produced. Over 300 million people have asthma worldwide. It is not curable but highly manageable with proper medication and trigger avoidance.",
        "symptoms": "• Wheezing (whistling sound when breathing)\n• Shortness of breath\n• Chest tightness\n• Coughing (especially at night or early morning)\n• Symptoms worsen with triggers (cold air, exercise, allergens)",
        "causes": "• Airway inflammation and hypersensitivity\n• Triggers: dust mites, pollen, pet dander, mold\n• Cold air or exercise\n• Air pollution and smoke\n• Respiratory infections\n• Strong emotions or stress\n• Certain medications (aspirin, beta-blockers)",
        "risk_factors": "• Allergic conditions (eczema, hay fever)\n• Family history of asthma\n• Smoking or secondhand smoke exposure\n• Air pollution exposure\n• Obesity\n• Occupational exposures (chemicals, dust)",
        "treatments": "• Reliever inhalers (short-acting bronchodilators)\n• Preventer inhalers (inhaled corticosteroids)\n• Long-acting bronchodilators\n• Leukotriene modifiers\n• Biologic therapies (severe asthma)\n• Avoid triggers",
        "medications": "• Salbutamol (Ventolin) inhaler — rescue bronchodilator\n• Budesonide inhaler — anti-inflammatory preventer\n• Fluticasone-Salmeterol — combination inhaler\n• Montelukast — leukotriene modifier (oral)\n• Prednisolone — for acute attacks",
        "prevention": "• Identify and avoid personal triggers\n• Keep home dust-free\n• Use air purifier\n• Avoid smoke exposure\n• Get flu vaccine annually\n• Monitor peak flow regularly",
        "lifestyle_tips": "• Always carry reliever inhaler\n• Use preventer inhaler daily even when well\n• Rinse mouth after using steroid inhaler\n• Use spacer with metered-dose inhaler\n• Breathing exercises (Buteyko technique)\n• Warm up before exercise\n• Wear scarf over mouth in cold weather",
        "when_to_see_doctor": "• Increasing reliever inhaler use (2+ times/week)\n• Nighttime symptoms\n• Severe breathlessness not improving with inhaler\n• Blue lips or fingernails (emergency)",
        "related_tests": "Spirometry (lung function), Peak flow measurement, Allergy tests, Chest X-ray, FeNO test",
    },

    # ══════════════════════════════════════════
    # MEDICAL TERMS
    # ══════════════════════════════════════════
    {
        "title": "HbA1c (Glycated Hemoglobin)",
        "slug": "hba1c",
        "type": "term",
        "category": "terms",
        "icon": "📖",
        "featured": False,
        "tags": "HbA1c, diabetes, blood sugar, 3 month average",
        "overview": "HbA1c (glycated hemoglobin) measures the average blood sugar level over the past 2-3 months. When blood glucose is high, it attaches to hemoglobin — the higher the sugar, the higher the HbA1c. It is the gold standard test for diabetes management. Results: Normal <5.7%, Prediabetes 5.7-6.4%, Diabetes ≥6.5%.",
        "symptoms": "• Not a symptom indicator — it is a diagnostic test result",
        "causes": "• HbA1c rises with consistently elevated blood sugar\n• Poorly controlled diabetes = high HbA1c\n• Well-controlled diabetes = HbA1c approaching normal",
        "risk_factors": "• Relevant for anyone with diabetes or prediabetes\n• Higher readings indicate higher complication risk",
        "treatments": "• HbA1c itself is a measurement, not a disease\n• Target for diabetics: below 7.0%\n• Lower with medication, diet, and exercise",
        "medications": "• All diabetes medications aim to lower HbA1c\n• Metformin, GLP-1 agonists, SGLT2 inhibitors are most effective",
        "prevention": "• Regular exercise reduces HbA1c by 0.5-1%\n• Low-carb diet reduces HbA1c significantly\n• Weight loss of 5-10% can normalize HbA1c in prediabetes",
        "lifestyle_tips": "• Test HbA1c every 3 months if diabetic, every 6 months if stable\n• Each 1% reduction in HbA1c reduces complications by 35%\n• Keep a blood sugar diary to understand patterns\n• Reducing rice/bread portions lowers HbA1c effectively",
        "when_to_see_doctor": "• HbA1c above 6.5%\n• HbA1c rising despite treatment\n• Any HbA1c above 8% needs urgent medication review",
        "related_tests": "Fasting glucose, Post-meal glucose, Fasting insulin, C-peptide",
    },

    {
        "title": "BMI (Body Mass Index)",
        "slug": "bmi",
        "type": "term",
        "category": "terms",
        "icon": "📖",
        "featured": False,
        "tags": "BMI, obesity, weight, overweight",
        "overview": "BMI is a simple calculation using height and weight (weight in kg ÷ height in m²) to categorize body weight. For Indians and Asians, lower thresholds apply: Underweight <18.5, Normal 18.5-22.9, Overweight 23-24.9, Obese ≥25. Standard WHO thresholds: Normal 18.5-24.9, Overweight 25-29.9, Obese ≥30.",
        "symptoms": "• BMI is a measurement, not a disease\n• High BMI is associated with: diabetes, hypertension, joint pain, sleep apnea, heart disease",
        "causes": "• BMI increases with: excessive calorie intake, physical inactivity, genetics, hormonal disorders",
        "risk_factors": "• BMI above 25 increases risk of: Type 2 diabetes, Hypertension, Heart disease, Sleep apnea, Osteoarthritis, Certain cancers",
        "treatments": "• For overweight/obese:\n  - Calorie-controlled diet\n  - Regular exercise\n  - Behavioral therapy\n  - Medications (Orlistat, Semaglutide)\n  - Bariatric surgery (BMI >40 or >35 with complications)",
        "medications": "• Orlistat — reduces fat absorption\n• Semaglutide (Ozempic/Wegovy) — significant weight loss\n• Naltrexone-bupropion — appetite suppression",
        "prevention": "• Balanced calorie intake\n• 150-300 minutes of moderate exercise per week\n• Limit processed foods, sugar, and saturated fats\n• Track weight weekly",
        "lifestyle_tips": "• Aim to lose 0.5-1 kg per week (safe rate)\n• Reduce portion sizes — use smaller plates\n• Eat slowly — brain takes 20 minutes to register fullness\n• Cut liquid calories (soft drinks, juices, alcohol)\n• Walk 10,000 steps daily\n• Sleep 7-8 hours — poor sleep increases appetite hormones",
        "when_to_see_doctor": "• BMI above 30\n• Rapid unexplained weight gain\n• BMI above 25 with diabetes, hypertension, or sleep apnea",
        "related_tests": "Waist circumference measurement, Body fat percentage, Blood glucose, Lipid profile, Thyroid function",
    },

    # ══════════════════════════════════════════
    # MEDICATIONS
    # ══════════════════════════════════════════
    {
        "title": "Metformin",
        "slug": "metformin",
        "type": "drug",
        "category": "drugs",
        "icon": "💊",
        "featured": False,
        "tags": "metformin, diabetes, blood sugar, glucophage",
        "overview": "Metformin is the most prescribed first-line medication for Type 2 diabetes worldwide. It works by reducing glucose production in the liver, improving insulin sensitivity, and slowing glucose absorption from the gut. It does NOT cause weight gain (unlike many diabetes drugs) and may even cause slight weight loss. Available as 500mg and 1000mg tablets.",
        "symptoms": "• Common side effects: nausea, diarrhea, stomach upset (especially when starting)\n• These usually improve after 2-4 weeks\n• Rare: lactic acidosis (serious — seek emergency care)",
        "causes": "• Prescribed for Type 2 diabetes and prediabetes\n• Also used for PCOS",
        "risk_factors": "• Should NOT be used in: kidney disease (eGFR <30), liver disease, heart failure, before contrast dye procedures",
        "treatments": "• Usual dose: 500mg twice daily with meals, gradually increasing to 2000mg/day\n• Take with food to reduce stomach side effects\n• Extended-release form (Metformin XR) has fewer GI side effects",
        "medications": "• Metformin 500mg, 850mg, 1000mg tablets\n• Metformin XR (extended release) — less GI upset\n• Combined with: Glimepiride, Sitagliptin, Dapagliflozin",
        "prevention": "• Take with meals to minimize side effects\n• Start with low dose and increase gradually\n• Stop before contrast CT scan and restart 48 hours after",
        "lifestyle_tips": "• Take with the first bite of a meal\n• If nausea occurs, reduce dose temporarily\n• Switch to XR version if regular causes upset\n• Monitor B12 levels annually — metformin reduces B12 absorption\n• Never double a missed dose\n• Continue with diet and exercise alongside metformin",
        "when_to_see_doctor": "• Severe nausea, vomiting, or abdominal pain\n• Muscle pain with weakness (lactic acidosis warning)\n• Any planned surgery or contrast scan\n• Blood sugar not improving after 3 months",
        "related_tests": "Blood glucose, HbA1c, Kidney function (before starting), Vitamin B12 (annually)",
    },

    # ══════════════════════════════════════════
    # VITAMINS & NUTRITION
    # ══════════════════════════════════════════
    {
        "title": "Vitamin D Deficiency",
        "slug": "vitamin-d-deficiency",
        "type": "disease",
        "category": "nutrition",
        "icon": "☀️",
        "featured": True,
        "tags": "vitamin D, bone, calcium, sunlight, deficiency",
        "overview": "Vitamin D deficiency is extremely common in India, affecting 70-90% of the population despite abundant sunshine. Vitamin D is essential for calcium absorption, bone strength, immune function, and mood regulation. Serum 25-OH Vitamin D below 20 ng/mL indicates deficiency; 20-29 ng/mL is insufficient; above 30 ng/mL is sufficient.",
        "symptoms": "• Fatigue and tiredness\n• Bone pain and tenderness\n• Muscle weakness and aches\n• Frequent infections\n• Depression and mood changes\n• Hair loss\n• Back pain\n• Slow wound healing\n• In children: rickets (bowed legs, soft skull bones)",
        "causes": "• Inadequate sunlight exposure (indoor lifestyle, sunscreen)\n• Dark skin (more melanin blocks UV)\n• Vegetarian/vegan diet (few dietary sources)\n• Obesity (fat stores vitamin D)\n• Kidney or liver disease (impairs activation)\n• Malabsorption (celiac, Crohn's disease)",
        "risk_factors": "• Working indoors\n• Dark skin\n• Obesity\n• Age over 65\n• Northern regions with less sunlight\n• Breastfed infants",
        "treatments": "• Oral Vitamin D3 supplements (cholecalciferol)\n• Loading dose for deficiency: 60,000 IU weekly x 8-12 weeks\n• Maintenance: 1000-2000 IU daily\n• Combine with Calcium if bone loss present\n• Sunlight exposure",
        "medications": "• Vitamin D3 (Cholecalciferol) 60,000 IU sachets — weekly loading\n• Vitamin D3 1000-2000 IU daily — maintenance\n• Calcitriol — active form, used in kidney disease\n• Calcium + Vitamin D3 combined supplements",
        "prevention": "• 15-20 minutes of sunlight on arms and legs daily (10am-3pm)\n• Eat fatty fish, eggs, fortified milk, mushrooms\n• Supplement 1000 IU/day if at risk\n• Annual Vitamin D test if deficient",
        "lifestyle_tips": "• Expose arms and legs to midday sun for 15-20 minutes\n• Don't shower immediately after sun exposure\n• Eat eggs (especially yolk), salmon, fortified milk\n• Take Vitamin D3 (not D2) with a fatty meal for better absorption\n• Take with Vitamin K2 if supplementing high doses (protects arteries)\n• Recheck levels after 3 months of supplementation",
        "when_to_see_doctor": "• Vitamin D below 10 ng/mL (severe deficiency)\n• Bone pain or fractures\n• Muscle weakness affecting daily activities\n• Children with growth concerns",
        "related_tests": "Serum 25-OH Vitamin D, Serum calcium, Phosphorus, PTH (parathyroid hormone), Bone density scan (DEXA)",
    },

    {
        "title": "Vitamin B12 Deficiency",
        "slug": "vitamin-b12-deficiency",
        "type": "disease",
        "category": "nutrition",
        "icon": "🔴",
        "featured": False,
        "tags": "B12, anemia, nerves, vegetarian, fatigue",
        "overview": "Vitamin B12 is essential for nerve function, red blood cell formation, and DNA synthesis. Deficiency is very common in vegetarians and vegans (B12 is found almost exclusively in animal products), elderly people, and those on metformin. Serum B12 below 200 pg/mL indicates deficiency. Left untreated, it causes irreversible nerve damage.",
        "symptoms": "• Fatigue and weakness\n• Pale or yellowish skin\n• Numbness or tingling in hands and feet\n• Balance problems and unsteady gait\n• Memory loss and confusion\n• Depression and mood changes\n• Sore, inflamed tongue\n• Shortness of breath\n• Vision disturbances",
        "causes": "• Vegetarian/vegan diet (no animal products)\n• Pernicious anemia (lack of intrinsic factor)\n• Gastric surgery or bypass\n• Long-term Metformin use (reduces absorption)\n• Celiac or Crohn's disease\n• Elderly (reduced stomach acid)",
        "risk_factors": "• Strict vegetarians and vegans\n• Age over 60\n• Long-term Metformin users\n• Gastric surgery history\n• Autoimmune gastritis",
        "treatments": "• Oral B12 supplements (cyanocobalamin or methylcobalamin)\n• B12 injections (for severe deficiency or malabsorption)\n• Dietary changes\n• Treat underlying cause",
        "medications": "• Methylcobalamin 500-1500mcg daily — preferred oral form\n• Cyanocobalamin 1000mcg — alternative oral form\n• Hydroxocobalamin injections — for pernicious anemia, monthly\n• Multivitamins with B12 — for maintenance",
        "prevention": "• Vegetarians: take B12 supplement daily\n• Eat fortified foods: nutritional yeast, fortified cereals\n• Annual B12 test if on Metformin\n• Elderly: supplement routinely\n• Breastfeeding vegans must supplement (infants at risk)",
        "lifestyle_tips": "• Sublingual (under tongue) B12 is better absorbed than regular tablets\n• Methylcobalamin is the active form — better for neurological symptoms\n• Cook with dairy products and eggs if lacto-vegetarian\n• Fermented foods have some B12 but not enough to rely on alone\n• Nutritional yeast is a good B12 source for vegans\n• Nerve damage can take months to recover — be patient with treatment",
        "when_to_see_doctor": "• B12 below 200 pg/mL\n• Numbness or tingling not improving\n• Balance or walking problems\n• Memory problems with low B12\n• Macrocytic anemia on CBC",
        "related_tests": "Serum Vitamin B12, CBC (looking for large red blood cells), Homocysteine, Methylmalonic acid, Peripheral nerve conduction studies",
    },

    # ══════════════════════════════════════════
    # BONES
    # ══════════════════════════════════════════
    {
        "title": "Osteoporosis",
        "slug": "osteoporosis",
        "type": "disease",
        "category": "bones",
        "icon": "🦴",
        "featured": False,
        "tags": "osteoporosis, bone density, fracture, calcium, DEXA",
        "overview": "Osteoporosis is a condition where bones become weak and brittle due to reduced bone density. A DEXA scan T-score below -2.5 confirms osteoporosis; -1.0 to -2.5 indicates osteopenia (early bone loss). Women lose bone rapidly after menopause. Over 200 million people worldwide have osteoporosis, causing 8.9 million fractures annually.",
        "symptoms": "• No symptoms in early stages\n• Back pain (caused by fractured vertebra)\n• Loss of height over time\n• Stooped posture\n• Bone fractures from minor falls or even coughing\n• Fragility fractures: hip, wrist, spine most common",
        "causes": "• Hormonal changes (menopause in women, low testosterone in men)\n• Calcium and Vitamin D deficiency\n• Long-term steroid use\n• Thyroid disease\n• Eating disorders\n• Sedentary lifestyle\n• Smoking and alcohol",
        "risk_factors": "• Female gender\n• Post-menopause\n• Age over 65\n• Small thin body frame\n• Family history of osteoporosis\n• Low calcium intake\n• Vitamin D deficiency\n• Smoking and alcohol\n• Long-term steroid use",
        "treatments": "• Calcium + Vitamin D supplementation\n• Bisphosphonates (Alendronate, Risedronate)\n• Denosumab injections\n• Hormone replacement therapy (for post-menopausal women)\n• Weight-bearing exercise\n• Fall prevention",
        "medications": "• Calcium carbonate 500mg + Vitamin D3 — foundation\n• Alendronate 70mg weekly — bisphosphonate\n• Risedronate 35mg weekly — alternative\n• Denosumab injection — every 6 months\n• Teriparatide — for severe cases (anabolic treatment)",
        "prevention": "• Adequate calcium intake: 1000-1200mg/day from food\n• Vitamin D: 1000-2000 IU daily\n• Weight-bearing exercise: walking, jogging, dancing\n• Resistance training 2-3x/week\n• Quit smoking\n• Limit alcohol\n• Prevent falls (non-slip mats, good lighting)",
        "lifestyle_tips": "• Eat dairy, green leafy vegetables, tofu, sesame seeds for calcium\n• Get 15 minutes of sunlight daily\n• Walk 30 minutes daily — weight-bearing exercise stimulates bone\n• Avoid cola drinks — phosphoric acid leaches calcium\n• Do balance exercises to prevent falls (tai chi, yoga)\n• Don't smoke — smoking reduces bone density significantly\n• Take calcium in split doses (max 500mg at a time) for better absorption",
        "when_to_see_doctor": "• Post-menopausal woman with risk factors\n• Any fragility fracture (fracture from minor impact)\n• Long-term steroid use\n• DEXA scan T-score below -1.5",
        "related_tests": "DEXA bone density scan, Serum calcium, Vitamin D, PTH, Thyroid function, Sex hormones (estrogen, testosterone)",
    },
]
