# Generated by Django 6.0.3 on 2026-03-19 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('urine_test', 'Urine Test'), ('xray', 'X-Ray'), ('mri', 'MRI Scan'), ('ct_scan', 'CT Scan'), ('ecg', 'ECG/EKG'), ('lipid_profile', 'Lipid Profile'), ('thyroid', 'Thyroid Function'), ('liver_function', 'Liver Function'), ('kidney_function', 'Kidney Function'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('file_type', models.CharField(default='pdf', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('analysis_summary', models.TextField(blank=True)),
                ('key_findings', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('lifestyle_advice', models.TextField(blank=True)),
                ('when_to_see_doctor', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('raw_analysis', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.medicalreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
